### ISSUE TITLE
As a user, I can edit a record of a patient's test results.

### ISSUE THREAD

**Issue by joey-chance** [AY2122S2-CS2103T-T11-1/tp#88]
so that I can easily change the information regarding the test result when it requires any revision.

The tasks needed to complete this feature include:
- [] Add edit command
- [] Parse user input
- [] Ui display
- [] Error handling for invalid or missing fields
